# Generated by Django 4.0.3 on 2022-04-08 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('Alimentacion', models.CharField(max_length=100, null=True)),
                ('Edad', models.PositiveIntegerField(null=True)),
                ('Fecha', models.DateField(null=True)),
                ('Sexo', models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=100, null=True)),
                ('Enfermedad', models.CharField(max_length=100, null=True)),
                ('Adoptante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
