# Generated by Django 4.0.3 on 2022-04-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascotas',
            options={'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AddField(
            model_name='mascotas',
            name='Especie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='Raza',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
