# Generated by Django 4.0.3 on 2022-04-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_mascotas_options_mascotas_especie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('Apellidos', models.CharField(max_length=100, null=True)),
                ('Edad', models.PositiveIntegerField(null=True)),
                ('Correo', models.CharField(max_length=100, null=True)),
                ('Telefono', models.PositiveIntegerField(null=True)),
                ('Domicilio', models.CharField(max_length=100, null=True)),
                ('Numero_de_mascotas', models.PositiveIntegerField(null=True)),
                ('Razones', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
