# Generated by Django 4.0.3 on 2022-05-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_vacunas_options_alter_vacunas_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascotas',
            name='Vacuna',
        ),
        migrations.DeleteModel(
            name='Vacunas',
        ),
    ]
