# Generated by Django 4.0.3 on 2022-05-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_mascotas_vacuna_delete_vacunas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Madopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('Sexo', models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], max_length=100, null=True)),
                ('Especie', models.CharField(max_length=100, null=True)),
                ('Raza', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(default='avatar.jpg', upload_to='Mascotas_images')),
            ],
        ),
    ]
